nama_provinsi:
    resource: "@NamaKotaProvinsiBundle/Controller"
    type:     annotation

nama_kota_kota:
    resource: "@NamaKotaKotaBundle/Controller"
    type:     annotation

nama_kota_home:
    resource: "@NamaKotaHomeBundle/Controller/"
    type:     annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
